![](https://www.dii.uchile.cl/wp-content/uploads/2021/06/Magi%CC%81ster-en-Ciencia-de-Datos.png)

**MDS7202: Laboratorio de Programación Científica para Ciencia de Datos**

### 👨‍🏫👩‍🏫 Cuerpo Docente:

- Profesores: Diego Cortez, Gabriel Iturra
- Auxiliares: Melanie Peña, Valentina Rojas
- Ayudantes: Nicolás Cabello, Cristopher Urbina

### 👨‍💻👩‍💻 Estudiantes:
- Estudiante n°1: Matías Godoy
- Estudiante n°2: Delaney Tello

_Por favor, lean detalladamente las instrucciones de la tarea antes de empezar a escribir._

---

---

## 📖 Enunciado

<div align="center">
    <img src='https://github.com/MDS7202/MDS7202/blob/main/recursos/2025-01/proyecto/proyecto.png?raw=true' style="border-radius: 12px"> 
</div>

En el competitivo universo de las bebidas gaseosas, la empresa **SodAI Drinks 🥤** ha logrado destacarse por su creatividad, diversidad de productos y enfoque centrado en el cliente. Ofrece una extensa gama de bebidas carbonatadas que abarca distintos segmentos del mercado: desde productos premium en presentaciones sofisticadas, hasta gaseosas accesibles para el consumo masivo, disponibles en diversos tamaños y tipos de envases. 

La compañía opera en múltiples regiones y zonas, sirviendo a una variedad de puntos de venta que incluyen desde tiendas de conveniencia y minimarkets hasta el canal frío tradicional. Cada tipo de cliente tiene sus particularidades: algunos reciben entregas hasta 4 veces por semana, mientras que otros son visitados por la fuerza de ventas solo una vez semanalmente. Esta diversidad de perfiles representa tanto una oportunidad como un desafío comercial: ¿cómo saber qué productos tienen más chances de ser comprados por cada cliente en un momento dado?

Con el objetivo de aumentar la facturación de forma inteligente y mejorar la eficiencia de su estrategia de ventas, **SodAI Drinks** decide crear una nueva célula interna de innovación: el equipo **Deep Drinkers 🤖**, cuyo propósito es aplicar ciencia de datos para anticiparse a las necesidades del cliente y potenciar el negocio desde una perspectiva basada en información.

El corazón de esta iniciativa es el desarrollo de un sistema predictivo personalizado para cada cliente. Para ello, **Deep Drinkers** convoca a un equipo de Data Scientists y especialistas en *machine learning* con una misión clara: construir un modelo predictivo que, cada semana, pueda estimar la probabilidad de compra de cada producto del portafolio para cada cliente activo.

El modelo deberá tener en cuenta múltiples factores, incluyendo:
- **Tipo de cliente**, ej. "TIENDA DE CONVENIENCIA", "MINIMARKET".
- **Frecuencia de entregas y visitas**, indicadores del nivel de actividad comercial.
- **Ubicación geográfica** (por región y zona).
- **Preferencias históricas de consumo**, inferidas por patrones de compra anteriores.
- **Características del producto**, como marca, categoría, segmento, tipo de envase y tamaño

El objetivo final es que, **cada semana**, se genere una tabla de productos priorizados: para cada cliente, un listado de productos ordenado por su probabilidad estimada de compra. Esta información será enviada al equipo comercial, que podrá usarla en call center, para incrementar las chances de concretar ventas al ofrecer justo lo que el cliente probablemente quiere comprar.

Este proyecto representa un cambio de paradigma en la forma en que **SodAI Drinks** gestiona su fuerza de ventas: de un enfoque reactivo y generalista, a uno proactivo, basado en datos y profundamente personalizado. Así, la empresa no solo espera aumentar su rentabilidad, sino también construir relaciones más sólidas con sus clientes, ofreciéndoles recomendaciones más relevantes y oportunas.

Para lograr lo anterior, el equipo **Deep Drinkers** contará con los siguientes conjuntos de datos, junto a sus respectivos atributos:

- **Datos transaccionales** (`transacciones.parquet`): contiene el historial de compras realizadas por los clientes.
	- `customer_id`: identificador único del cliente que realizó la compra.
	- `product_id`: identificador único del producto comprado.
	- `purchase_date`: fecha en que se realizó la transacción.
	- `order_id`: identificar de la orden de su pedido.
	- `payment`	monto total pagado por la transacción.

- **Datos de clientes** (`clientes.parquet`): incluye las características de cada cliente.
	- `customer_id`: identificador único del cliente.
	- `region_id`: identificador de la región geográfica donde se encuentra el cliente.
	- `customer_type`: tipo de cliente según el canal comercial, por ejemplo, “TIENDA DE CONVENIENCIA”.
	- `Y`: coordenada geográfica de latitud.
	- `X`: coordenada geográfica de longitud.
	- `num_deliver_per_week`: cantidad de entregas semanales que recibe el cliente.
	- `num_visit_per_week`: frecuencia de visitas de la fuerza de ventas por semana.

- **Datos de productos** (`productos.parquet`): describe las características de los productos del portafolio.
	- `product_id`: identificador único del producto.
	- `brand`: marca comercial del producto.
	- `category`: categoría general del producto, como “BEBIDAS CARBONATADAS”.
	- `sub_category`: subcategoría dentro de la categoría principal, por ejemplo, “GASEOSAS”.
	- `segment`: segmento de mercado al que pertenece el producto, como “PREMIUM”.
	- `package`: tipo de envase del producto.
	- `size`: tamaño del producto en litros.

## 📚 Reglas

<center>
<img src="https://media1.tenor.com/m/0Qtv_cQ4ITsAAAAd/necohaus-grey-name.gif" width="450">



El proyecto consta de **dos entregas parciales** y una **entrega final** en donde la primera entrega la idea es poder reflejar lo aprendido durante la primera mitad del curso, que será sobre los contenidos relacionados a *machine learning*, la segunda será sobre los contenidos de la segunda mitad del curso relacionados a *MLOps* y por último la entrega final constará de dos partes, donde la primera será relacionada con experimentación sobre nuevos datasets que serán disponibilizados durante las últimas semanas del curso de manera incremental y una segunda parte que será el informe final escrito que deberá explicar el desarrollo del proyecto completo, como tambien los resultados y análisis de los experimentos realizados sobre los datasets incrementales. La idea es que todo el código esté desarrollado durante las primeras dos entregas y luego en la entrega final sólo se ejecute el código sobre nuevos conjuntos de datos.

La idea de generar el proyecto por etapas es poder aliviar la carga de trabajo en las últimas semanas del semestre donde sabemos que están muy cargado con entregas, pruebas y exámenes de otros ramos, y así garantizamos que habiendo la desarrollado las dos primeras entregas parciales, tendrán el grueso del proyecto listo para luego experimentar y documentar.

---
### **Fechas de entrega**
- **Entrega parcial 1**: 12 de Septiembre
- **Entrega parcial 2**: Por definir
- **Entrega final**: Por definir

---

### **Requisitos del proyecto**
- **Grupos**: Formar equipos de **2 personas**. No se aceptarán trabajos individuales o grupos con más integrantes.
- **Consultas**: Cualquier duda fuera del horario de clases debe ser planteada en el foro correspondiente. Los mensajes enviados al equipo docente serán respondidos únicamente por este medio. Por favor, revisen las respuestas anteriores en el foro antes de realizar nuevas consultas.
- **Plagio**: La copia o reutilización no autorizada de trabajos de otros grupos está **estrictamente prohibida**. El incumplimiento de esta norma implicará la anulación inmediata del proyecto y una posible sanción académica.
- **Material permitido**: Pueden usar cualquier material del curso, ya sea notas, lecturas, códigos, o referencias proporcionadas por los docentes, que consideren útil para el desarrollo del proyecto.

---

### **Entregables y etapas**

#### **1. Entrega Parcial 1**  
- Dispondrán de los archivos de datos **productos.parquet**, **clientes.parquet** y **transacciones.parquet** para el modelamiento inicial.  
- Utilizarán estos archivos para desarrollar lo solicitado para la entrega 1. 
- En esta etapa, se espera que apliquen todos los conocimientos aprendidos durante la primera parte del curso relacionados con *machine learning*.
- **Informe**: No se exige un avance del informe en esta etapa, sólo un notebook con su desarrollo actual, pero se **recomienda comenzar** a redactar el informe final en paralelo para disminuir la carga académica en las etapas posteriores.  

#### **2. Entrega Parcial 2**  
- En esta entrega, deberán aplicar los conocimientos aprendidos durante la segunda mitad del curso sobre *MLOps*  
- Se espera que implementen estos conocimientos para desplegar su modelo elegido en la primera entrega y crear *pipelines* automatizados que simulen un entorno productivo.
- **Informe**: similar a la primera etapa, no se exige un avance del informe, pero se **recomienda avanzar con su redacción** para evitar una acumulación de trabajo en la etapa final.  

#### **3. Entrega Final**  
- En la entrega final, deberán realizar dos etapas:
	- La primera etapa es sobre experimentación utilizando datasets incrementales que se irán disponibilizando de manera parcial, para que vayan generando predicciones con su modelo ya desplegado. El objetivo de esta etapa es poder testear su solución *end-to-end* y que vayan analizando los resultados obtenidos a medida que se van agregando más datos.
	- La segunda etapa consiste en redactar un informe final que deberá explicar el desarrollo completo de tu proyecto y un análisis profundo de sus resultados de experimentación. Este informe debera incluir a lo menos las siguientes secciones:
		- Análisis exploratorio de datos  
		- Metodología aplicada  
		- Selección y entrenamiento de modelos  
		- Evaluación de resultados  
		- Optimización de modelos
		- Interpretabilidad
		- Re-entrenamiento
		- Tracking con MLFlow
		- Creación de la aplicación web con Gradio y FastAPI

Es **altamente recomendable** ir redactando el informe en paralelo al desarrollo de los modelos para garantizar que toda la información relevante quede documentada adecuadamente.  

### Nota Final

La calificación final de su proyecto se calculará utilizando la siguiente ponderación: 

$$Nota Final = 0.30 * EntregaParcial1 + 0.40 * EntregaParcial2 + 0.30 * EntregaFinal$$

---

### **Instrucciones importantes**

1. **Formato del informe**:  
   - El informe debe estar integrado dentro de un **Jupyter Notebook**. No es necesario subirlo a una plataforma externa, pero debe cumplir con los siguientes requisitos:  
     - Estructura clara y ordenada.  
     - Código acompañado de explicaciones detalladas.  
     - Resultados presentados de forma visual y analítica.  

2. **Descuento por informes deficientes**:  
   - Cualquier sección del informe que no tenga una explicación adecuada o no respete el formato será penalizada con un descuento en la nota. Esto incluye código sin comentarios o análisis que no sean coherentes con los resultados presentados.
   - Comentarios sin formatear de ChatGPT o herramientas similares serán penalizados (e.g: "Inserta tu modelo acá", etc.)

# 📬 Entrega Parcial 1 (30% del Proyecto)

### 📪 Fecha de Entrega: 12 de Septiembre

## 📌 Abstract [0.25 puntos]

<center>
<img src="https://i.redd.it/h5ptnsyabqvd1.gif" width="400" height="300">

En esta sección, deben redactar un Abstract claro y conciso para su proyecto. El Abstract debe responder a las siguientes preguntas clave:

- **Descripción del problema**: ¿Cuál es el objetivo del proyecto? ¿Qué se intenta predecir o analizar?
- **Datos de entrada**: ¿Qué datos tienen disponibles? ¿Cuáles son sus principales características?
- **Métrica de evaluación**: ¿Cómo medirán el desempeño de sus modelos? Expliquen por qué eligieron esta métrica basándose en el análisis exploratorio de los datos.
- **Modelos y transformaciones**: ¿Qué modelos utilizarán y por qué? ¿Qué transformaciones o preprocesamientos aplicaron a los datos?
- **Resultados generales**: ¿El modelo final cumplió con los objetivos del proyecto? ¿Cuáles fueron las conclusiones más importantes?

**Importante**: Escriban esto despues de haber resuelto el resto de la tarea.

> [Escriba aquí su Abstract]

## 📌 Pre-procesamiento [0.5 puntos]

<center>
<img src="https://media0.giphy.com/media/10zsjaH4g0GgmY/giphy.gif?cid=6c09b9523xtlunksc9amikw09zk1bmiqwjqnt70ae82rk877&ep=v1_gifs_search&rid=giphy.gif&ct=g" width="400" height="300">

Tal como en muchos otros problemas de negocio, los datos probablemente deben ser pre procesados antes de aplicar cualquier técnica de analítica. Bajo esa premisa, en esta sección deben desarrollar código que les permita **preparar los datos** de tal forma que les permita resolver el problema planteado. Para esto, pueden aplicar procesamientos como:

- Transformaciones de tipo de dato (str, int, etc)
- Cruce de información
- Eliminación de duplicados
- Filtros de fila y/o columnas

*Hint: ¿Qué forma debería tener la data para resolver un problema de aprendizaje supervisado?*

Todo proceso llevado a cabo debe estar bien documentado y justificado en el informe, explicando el por qué se decidió realizar en funcion de los datos presentados y los objetivos planteados del proyecto.

In [1]:
import pandas as pd
df_clientes = pd.read_parquet("clientes.parquet", engine="fastparquet")
df_productos = pd.read_parquet("productos.parquet", engine="fastparquet")
df_transacciones = pd.read_parquet("transacciones.parquet", engine="fastparquet")

## Transformaciones tipos de datos

In [2]:
df_clientes.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1569 entries, 10705 to 12273
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           1569 non-null   int64
 1   region_id             1569 non-null   int64
 2   zone_id               1569 non-null   int64
 3   customer_type         1569 non-null   object
 4   Y                     1569 non-null   float64
 5   X                     1568 non-null   float64
 6   num_deliver_per_week  1569 non-null   int64
 7   num_visit_per_week    1569 non-null   int64
dtypes: float64(2), int64(5), object(1)
memory usage: 110.3+ KB

In [3]:
df_clientes.head()

,customer_id,region_id,zone_id,customer_type,Y,X,num_deliver_per_week,num_visit_per_week
10705,256017,80,5148,ABARROTES,-46.474800,-108.045140,1,1
10706,255780,80,5148,ABARROTES,-46.520282,-107.961052,1,1
10707,254655,80,5148,ABARROTES,-46.537640,-107.909280,1,1
10708,254445,80,5148,ABARROTES,-46.543526,-107.917954,2,1
10709,254403,80,5148,ABARROTES,-46.540856,-107.905792,3,1

In [4]:
df_clientes['customer_type'] = df_clientes['customer_type'].astype("string")

In [5]:
df_productos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 971 entries, 0 to 970
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    971 non-null    int64
 1   brand         971 non-null    object
 2   category      971 non-null    object
 3   sub_category  971 non-null    object
 4   segment       971 non-null    object
 5   package       971 non-null    object
 6   size          971 non-null    float64
dtypes: float64(1), int64(1), object(5)
memory usage: 53.2+ KB

In [6]:
df_productos.head()

,product_id,brand,category,sub_category,segment,package,size
0,34092,Brand 31,BEBIDAS CARBONATADAS,GASEOSAS,PREMIUM,BOTELLA,0.66
1,57290,Brand 31,BEBIDAS CARBONATADAS,GASEOSAS,PREMIUM,BOTELLA,0.66
2,56714,Brand 31,BEBIDAS CARBONATADAS,GASEOSAS,PREMIUM,BOTELLA,0.66
3,296616,Brand 31,BEBIDAS CARBONATADAS,GASEOSAS,PREMIUM,BOTELLA,0.66
4,60854,Brand 31,BEBIDAS CARBONATADAS,GASEOSAS,PREMIUM,BOTELLA,0.25

In [7]:
df_productos['category'] = df_productos['category'].astype("string")
df_productos['sub_category'] = df_productos['sub_category'].astype("string")
df_productos['segment'] = df_productos['segment'].astype("string")
df_productos['package'] = df_productos['package'].astype("string")
df_productos['brand'] = df_productos['brand'].astype("string")

In [8]:
df_transacciones.info()

<class 'pandas.core.frame.DataFrame'>
Index: 254936 entries, 124 to 7712548
Data columns (total 5 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   customer_id    254936 non-null  int64
 1   product_id     254936 non-null  int64
 2   order_id       254936 non-null  int64
 3   purchase_date  254936 non-null  datetime64[ns]
 4   items          254936 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(3)
memory usage: 11.7 MB

In [9]:
df_transacciones.head()

     customer_id  product_id  order_id purchase_date     items
124        61353       61364    411145    2024-04-27 -0.333333
127        61899        1370    411156    2024-04-27  3.666667
344       154077       30500    417911    2024-04-29  2.333333
349       164337       56714    418100    2024-04-29 -2.333333
354       172056       61672    407162    2024-04-26  1.000000

## Cruce de información

In [10]:
#como los datos de transacciones tienen los id de los clientes y productos, se puede hacer merge de las otras dos tablas sobre esta
#de este modo, tenemos una tabla general con toda la info del cliente y el producto de la transacción
df = df_transacciones.merge(df_clientes, on='customer_id', how='left').merge(df_productos, on='product_id', how='left')

In [11]:
df.head()

,customer_id,product_id,order_id,purchase_date,items,region_id,zone_id,customer_type,Y,X,num_deliver_per_week,num_visit_per_week,brand,category,sub_category,segment,package,size
0,61353,61364,411145,2024-04-27,-0.333333,80,5148,ABARROTES,-46.558718,-107.860564,3,1,Brand 35,BEBIDAS CARBONATADAS,GASEOSAS,MEDIUM,BOTELLA,1.00
1,61899,1370,411156,2024-04-27,3.666667,80,5148,MAYORISTA,-46.557632,-107.896470,3,1,Brand 34,BEBIDAS CARBONATADAS,GASEOSAS,MEDIUM,BOTELLA,1.00
2,154077,30500,417911,2024-04-29,2.333333,80,5148,ABARROTES,-46.543598,-107.874170,3,1,Brand 31,BEBIDAS CARBONATADAS,GASEOSAS,PREMIUM,LATA,0.31
3,164337,56714,418100,2024-04-29,-2.333333,80,5148,ABARROTES,-46.549960,-107.863088,3,1,Brand 31,BEBIDAS CARBONATADAS,GASEOSAS,PREMIUM,BOTELLA,0.66
4,172056,61672,407162,2024-04-26,1.000000,80,5148,MAYORISTA,-46.564528,-107.927651,4,1,Brand 34,BEBIDAS CARBONATADAS,GASEOSAS,MEDIUM,LATA,0.25

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 254936 entries, 0 to 254935
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   customer_id           254936 non-null  int64
 1   product_id            254936 non-null  int64
 2   order_id              254936 non-null  int64
 3   purchase_date         254936 non-null  datetime64[ns]
 4   items                 254936 non-null  float64
 5   region_id             254936 non-null  int64
 6   zone_id               254936 non-null  int64
 7   customer_type         254936 non-null  string
 8   Y                     254936 non-null  float64
 9   X                     254936 non-null  float64
 10  num_deliver_per_week  254936 non-null  int64
 11  num_visit_per_week    254936 non-null  int64
 12  brand                 254936 non-null  string
 13  category              254936 non-null  string
 14  sub_category          254936 non-null  string
 15  segment               254936 non-null  string
 16  package               254936 non-null  string
 17  size                  254936 non-null  float64
dtypes: datetime64[ns](1), float64(4), int64(7), string(6)
memory usage: 35.0 MB

## Eliminación de duplicados

In [13]:
# haremos búsqueda y eliminación de duplicados para no darle más peso a cierta observación en la parte del EDA y modelo de este proyecto
duplicados = df.duplicated()
duplicados[duplicados==True]

344       True
673       True
1209      True
1953      True
2017      True
          ...
253227    True
253483    True
253608    True
254095    True
254163    True
Length: 885, dtype: bool

In [14]:
df=df.drop_duplicates()
duplicados = df.duplicated()
duplicados[duplicados==True]

Series([], dtype: bool)

## Filtos de filas y/o columnas

In [16]:
df.head()

,customer_id,product_id,order_id,purchase_date,items,region_id,zone_id,customer_type,Y,X,num_deliver_per_week,num_visit_per_week,brand,category,sub_category,segment,package,size
0,61353,61364,411145,2024-04-27,-0.333333,80,5148,ABARROTES,-46.558718,-107.860564,3,1,Brand 35,BEBIDAS CARBONATADAS,GASEOSAS,MEDIUM,BOTELLA,1.00
1,61899,1370,411156,2024-04-27,3.666667,80,5148,MAYORISTA,-46.557632,-107.896470,3,1,Brand 34,BEBIDAS CARBONATADAS,GASEOSAS,MEDIUM,BOTELLA,1.00
2,154077,30500,417911,2024-04-29,2.333333,80,5148,ABARROTES,-46.543598,-107.874170,3,1,Brand 31,BEBIDAS CARBONATADAS,GASEOSAS,PREMIUM,LATA,0.31
3,164337,56714,418100,2024-04-29,-2.333333,80,5148,ABARROTES,-46.549960,-107.863088,3,1,Brand 31,BEBIDAS CARBONATADAS,GASEOSAS,PREMIUM,BOTELLA,0.66
4,172056,61672,407162,2024-04-26,1.000000,80,5148,MAYORISTA,-46.564528,-107.927651,4,1,Brand 34,BEBIDAS CARBONATADAS,GASEOSAS,MEDIUM,LATA,0.25

## 📌 EDA [0.5 puntos]

<center>
<img src="https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExbHZ6aGdkd21tYTI3cW8zYWhyYW5wdGlyb2s3MmRzeTV0dzQ1NWlueiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3k1hJubTtOAKPKx4k3/giphy.gif" width="400" height="200">

En esta sección, se debe realizar un análisis exploratorio de los datos para comprender su estructura, detectar posibles problemas y obtener información relevante para el entrenamiento de los modelos. La idea es que puedan detectar **patrones en los datos** que les permitan resolver el problema con mayor facilidad.

Se deben responder preguntas a partir de lo que puedan visualizar/obtener, por ejemplo:

- Clientes y productos

    - ¿Cuántos clientes únicos hay en el dataset?

    - ¿Cuántos productos únicos se encuentran en los datos?

- Periodo y frecuencia

    - ¿De qué periodo es la información disponible?

    - ¿Cuál es la frecuencia de los registros (diaria, semanal, mensual, etc.)?

- Calidad de los datos

    - ¿Existen valores nulos en el dataset? ¿Cuántos? ¿Cómo se pueden tratar?

    - ¿Hay datos raros, como cantidades negativas o inconsistencias? Genere tests de validación para identificar estos problemas.

- Patrones de compra

    - ¿Cuántos productos compra en promedio cada cliente semana a semana?

    - ¿Cuántas transacciones ha realizado cada cliente?

    - ¿Cuál es el periodo de recompra promedio de cada SKU?

## Clientes y productos

In [17]:
df.head()

,customer_id,product_id,order_id,purchase_date,items,region_id,zone_id,customer_type,Y,X,num_deliver_per_week,num_visit_per_week,brand,category,sub_category,segment,package,size
0,61353,61364,411145,2024-04-27,-0.333333,80,5148,ABARROTES,-46.558718,-107.860564,3,1,Brand 35,BEBIDAS CARBONATADAS,GASEOSAS,MEDIUM,BOTELLA,1.00
1,61899,1370,411156,2024-04-27,3.666667,80,5148,MAYORISTA,-46.557632,-107.896470,3,1,Brand 34,BEBIDAS CARBONATADAS,GASEOSAS,MEDIUM,BOTELLA,1.00
2,154077,30500,417911,2024-04-29,2.333333,80,5148,ABARROTES,-46.543598,-107.874170,3,1,Brand 31,BEBIDAS CARBONATADAS,GASEOSAS,PREMIUM,LATA,0.31
3,164337,56714,418100,2024-04-29,-2.333333,80,5148,ABARROTES,-46.549960,-107.863088,3,1,Brand 31,BEBIDAS CARBONATADAS,GASEOSAS,PREMIUM,BOTELLA,0.66
4,172056,61672,407162,2024-04-26,1.000000,80,5148,MAYORISTA,-46.564528,-107.927651,4,1,Brand 34,BEBIDAS CARBONATADAS,GASEOSAS,MEDIUM,LATA,0.25

In [15]:
print(f"Hay un total de {len(df["customer_id"].unique())} clientes unicos en el dataset")

Hay un total de 1490 clientes unicos en el dataset

In [16]:
print(f"Hay un total de {len(df["product_id"].unique())} productos unicos en el dataset")

Hay un total de 114 productos unicos en el dataset

## Periodo y Frecuencia

In [17]:
print(f"Menor fecha en el dataset: {min(df["purchase_date"])}")
print(f"Máxima fecha en el dataset: {max(df["purchase_date"])}")

Menor fecha en el dataset: 2024-01-01 00:00:00
Máxima fecha en el dataset: 2024-12-31 00:00:00

In [18]:
len(df["purchase_date"].unique())

366

In [19]:
df["purchase_date"].unique()

<DatetimeArray>
['2024-04-27 00:00:00', '2024-04-29 00:00:00', '2024-04-26 00:00:00',
 '2024-04-28 00:00:00', '2024-04-30 00:00:00', '2024-04-25 00:00:00',
 '2024-01-30 00:00:00', '2024-01-26 00:00:00', '2024-01-24 00:00:00',
 '2024-01-28 00:00:00',
 ...
 '2024-11-27 00:00:00', '2024-11-26 00:00:00', '2024-11-25 00:00:00',
 '2024-09-28 00:00:00', '2024-02-11 00:00:00', '2024-03-29 00:00:00',
 '2024-09-08 00:00:00', '2024-09-07 00:00:00', '2024-11-05 00:00:00',
 '2024-11-04 00:00:00']
Length: 366, dtype: datetime64[ns]

el periodo de los datos es el año completo de 2024

La frecuencia de la data es diaria

## Calidad de los datos

In [20]:
#verificamos si hay nan para eliminarlos
df.isna().any().any()

np.False_

In [21]:
print(df_clientes.isna().any().any())
print(df_productos.isna().any().any())
print(df_transacciones.isna().any().any())

True
False
False

In [22]:
df_clientes.isna().sum()

customer_id             0
region_id               0
zone_id                 0
customer_type           0
Y                       0
X                       1
num_deliver_per_week    0
num_visit_per_week      0
dtype: int64

hay un valor nulo en una observación de la tabla clientes

In [23]:

def validar_clientes(df_clientes):
    print("=== Validación Clientes ===")

    coords_invalidas = df_clientes[
        (df_clientes['Y'] < -90) | (df_clientes['Y'] > 90) |
        (df_clientes['X'] < -180) | (df_clientes['X'] > 180)
    ]
    print("Clientes con coordenadas inválidas:", len(coords_invalidas))
    
    # Frecuencias negativas
    entregas_invalidas = df_clientes[(df_clientes['num_deliver_per_week'] < 0) ]
    print("Clientes con entregas negativas:", len(entregas_invalidas))

    # Frecuencias negativas
    entregas_invalidas = df_clientes[(df_clientes['num_visit_per_week'] < 0)]
    print("Clientes con visitas negativas:", len(entregas_invalidas))

    # Verificar si algún zone_id está asociado a más de un region_id
    zonas_por_region = df_clientes.groupby("zone_id")["region_id"].nunique().reset_index(name="num_regiones")

    # Filtrar zonas conflictivas (más de una región asociada)
    zonas_conflictivas = zonas_por_region[zonas_por_region["num_regiones"] > 1]

    print("Zonas asociadas a múltiples regiones:")
    print(zonas_conflictivas)

    if not zonas_conflictivas.empty:
        detalle_conflictivas = df_clientes[df_clientes["zone_id"].isin(zonas_conflictivas["zone_id"])]
        print("\nDetalle de zonas conflictivas:")
        print(detalle_conflictivas.sort_values(["zone_id", "region_id"]))
    
       

def validar_productos(df_productos):
    print("\n=== Validación Productos ===")
    tamanos_invalidos = df_productos[df_productos['size'] <= 0]
    print("Productos con tamaño inválido:", len(tamanos_invalidos))
    # Verificar si alguna sub_category está asociada a más de una category
    subcat_por_cat = (
        df_productos.groupby("sub_category")["category"]
        .nunique()
        .reset_index(name="num_categorias")
    )

    # Filtrar subcategorías conflictivas
    subcat_conflictivas = subcat_por_cat[subcat_por_cat["num_categorias"] > 1]

    print("Subcategorías asociadas a múltiples categorías:")
    print(subcat_conflictivas)

    # Opcional: ver detalle de esas subcategorías conflictivas
    if not subcat_conflictivas.empty:
        detalle_conflictivas = df_productos[
            df_productos["sub_category"].isin(subcat_conflictivas["sub_category"])
        ]
        print("\nDetalle de subcategorías conflictivas:")
        print(detalle_conflictivas.sort_values(["sub_category", "category"]))

def validar_transacciones(df_transacciones):
    print("\n=== Validación Transacciones ===") 
    # Cantidades negativas o cero
    items_invalidos = df_transacciones[df_transacciones['items'] <= 0]
    print("Transacciones con items inválidos:", len(items_invalidos))
    



validar_clientes(df_clientes)
validar_productos(df_productos)
validar_transacciones(df_transacciones)

=== Validación Clientes ===
Clientes con coordenadas inválidas: 3
Clientes con entregas negativas: 0
Clientes con visitas negativas: 0
Zonas asociadas a múltiples regiones:
Empty DataFrame
Columns: [zone_id, num_regiones]
Index: []

=== Validación Productos ===
Productos con tamaño inválido: 0
Subcategorías asociadas a múltiples categorías:
  sub_category  num_categorias
2        JUGOS               2

Detalle de subcategorías conflictivas:
     product_id     brand                 category sub_category segment  \
608       52136  Brand 19     BEBIDAS CARBONATADAS        JUGOS    HIGH
85        58830  Brand 18  BEBIDAS NO CARBONATADAS        JUGOS     LOW
86        58832  Brand 18  BEBIDAS NO CARBONATADAS        JUGOS     LOW
87        56296  Brand 18  BEBIDAS NO CARBONATADAS        JUGOS     LOW
88        56208  Brand 18  BEBIDAS NO CARBONATADAS        JUGOS     LOW
..          ...       ...                      ...          ...     ...
925       56268  Brand 50  BEBIDAS NO CARBONATADAS        JUGOS     LOW
926       61372  Brand 50  BEBIDAS NO CARBONATADAS        JUGOS     LOW
927       61370  Brand 50  BEBIDAS NO CARBONATADAS        JUGOS     LOW
928       56302  Brand 50  BEBIDAS NO CARBONATADAS        JUGOS     LOW
929       60668  Brand 11  BEBIDAS NO CARBONATADAS        JUGOS     LOW

     package  size
608     LATA  0.50
85   BOTELLA  0.33
86   BOTELLA  0.33
87   BOTELLA  0.50
88   BOTELLA  0.25
..       ...   ...
925  BOTELLA  0.50
926  BOTELLA  0.50
927  BOTELLA  2.00
928  BOTELLA  3.00
929  BOTELLA  1.00

[229 rows x 7 columns]

=== Validación Transacciones ===
Transacciones con items inválidos: 8385

## Patrones de compra

In [24]:
# Crear columna de año-semana
df['year_week'] = df['purchase_date'].dt.strftime('%Y-%U')

# Calcular productos comprados por cliente y semana
productos_por_semana = df.groupby(['customer_id', 'year_week'])['product_id'].nunique().reset_index(name='productos en semana')

# Promedio de productos por cliente (en todas sus semanas activas)
promedio_productos_cliente = productos_por_semana.groupby('customer_id')['productos en semana'].mean().reset_index(name='Promedio Prod por semana')

promedio_productos_cliente

      customer_id  Promedio Prod por semana
0           25734                  4.600000
1           25743                  6.788462
2           25749                 15.846154
3           56868                  2.681818
4           56871                  3.764706
...           ...                       ...
1485       253308                  6.000000
1486       253335                  2.000000
1487       253557                  4.500000
1488       457455                  2.642857
1489      2061063                  4.500000

[1490 rows x 2 columns]

Como son muchos clientes, haremos un histograma con plotly para visualizar la distribución de la cantidad de productos por semana.

In [25]:
import plotly.express as px

fig = px.histogram(
    promedio_productos_cliente,
    x="Promedio Prod por semana",
    nbins=30,  # número de bins (ajusta según prefieras)
    title="Distribución del promedio semanal de productos por cliente",
    labels={"promedio_productos_semana": "Promedio de productos comprados por semana"}
)

fig.update_layout(
    bargap=0.1,
    xaxis_title="Promedio de productos/semana",
    yaxis_title="Número de clientes"
)

fig.show()

In [26]:
transacciones_cliente = df.groupby('customer_id')['order_id'].nunique().reset_index(name='total transacciones')
transacciones_cliente

      customer_id  total transacciones
0           25734                   15
1           25743                  121
2           25749                  107
3           56868                   25
4           56871                   36
...           ...                  ...
1485       253308                    1
1486       253335                    1
1487       253557                    2
1488       457455                   15
1489      2061063                   30

[1490 rows x 2 columns]

In [27]:
fig = px.histogram(
    transacciones_cliente,
    x="total transacciones",
    nbins=30,  # número de bins (ajusta según prefieras)
    title="Distribución de total de transacciones por cliente",
    labels={"total transacciones": "Total de transacciones por cliente"}
)

fig.update_layout(
    bargap=0.1,
    xaxis_title="Numero de Productos",
    yaxis_title="Cantidad de clientes"
)

fig.show()

In [28]:
# Ordenar por producto y fecha
df_sorted = df.sort_values(['product_id', 'purchase_date'])

# Calcular diferencia de días entre compras consecutivas por producto
df_sorted['diff_days'] = df_sorted.groupby('product_id')['purchase_date'].diff().dt.days

# Promedio de días de recompra por SKU (product_id)
recompra_promedio = df_sorted.groupby('product_id')['diff_days'].mean().reset_index(name='periodo_recompra_promedio')

recompra_promedio

     product_id  periodo_recompra_promedio
0            60                   0.623711
1           124                   0.277651
2          1206                 112.500000
3          1304                   0.016679
4          1370                   0.009702
..          ...                        ...
109       63360                   0.094937
110       63418                   0.273333
111       63510                   0.015510
112       63538                   0.348837
113       63540                   0.928571

[114 rows x 2 columns]

In [29]:

fig = px.histogram(
    recompra_promedio,
    x="periodo_recompra_promedio",
    nbins=40,  # ajusta el número de bins según distribución
    title="Distribución del periodo de recompra promedio por SKU",
    labels={"periodo_recompra_promedio": "Periodo de recompra promedio (días)"}
)

fig.update_layout(
    bargap=0.1,
    xaxis_title="Días entre compras",
    yaxis_title="Número de productos (SKU)"
)

fig.show()

## 📌 Holdout [0.25 puntos]

Para evaluar correctamente el modelo y garantizar su capacidad de generalización, se deben dividir los datos en tres conjuntos: 
- `Entrenamiento` : Para ajustar los parámetros.
- `Validación`: Para optimizar hiperparámetros y seleccionar el mejor modelo.
- `Prueba` : Para evaluar el rendimiento final en datos no vistos.

👀 **Hint**: *Recuerde que los datos tienen una temporalidad que debe considerarse al momento de separarlos, para evitar fugas de información. Es importante justificar la estrategia de partición elegida y visualizar la distribución temporal de los conjuntos generados*

In [30]:
df = df.sort_values('purchase_date')  

n = len(df)
train_end = int(n * 0.7)
val_end = int(n * 0.85) 

train_df = df.iloc[:train_end]      
val_df = df.iloc[train_end:val_end] 
test_df = df.iloc[val_end:]         

print(f"Train: {len(train_df)}, Fechas: {train_df['purchase_date'].min()} a {train_df['purchase_date'].max()}")
print(f"Validation: {len(val_df)}, Fechas: {val_df['purchase_date'].min()} a {val_df['purchase_date'].max()}")
print(f"Test: {len(test_df)}, Fechas: {test_df['purchase_date'].min()} a {test_df['purchase_date'].max()}")


#Se decidió separar el conjunto según fecha, para no perder relación temporal entre los datos, ya que se quieren hacer predicciones a futuro.

Train: 177835, Fechas: 2024-01-01 00:00:00 a 2024-10-05 00:00:00
Validation: 38108, Fechas: 2024-10-05 00:00:00 a 2024-11-23 00:00:00
Test: 38108, Fechas: 2024-11-23 00:00:00 a 2024-12-31 00:00:00

## 📌 Feature Engineering [0.5 puntos]

<center>
<img src="https://i.imgur.com/CmXZSSC.gif" width="300" height="200">

En esta sección, se deben construir pipelines para automatizar el preprocesamiento de los datos, lo cual garantizará que el flujo de trabajo sea reproducible y eficiente para esta entrega y las futuras. El objetivo es aplicar una serie de transformaciones en un orden definido para asegurar que los datos estén listos para los modelos a entrenar. El pipeline final debe incluir las técnicas de pre-procesamiento que se deben aplicar a los distintos datos (según lo que consideren necesario para el problema). Por ejemplo:

- **Imputación de valores nulos**: Manejo de datos faltantes mediante estrategias adecuadas (media, mediana, moda, interpolación, etc.). 

- **Transformaciones personalizadas**: Uso de ColumnTransformer para aplicar diferentes transformaciones a columnas específicas.

- **Codificación de variables categóricas**: Convertir datos categóricos a un formato numérico adecuado (One-Hot Encoding, Label Encoding, etc.).

- **Discretización de variables**: Conversión de variables numéricas continuas en categorías si son relevantes para el desempeño del modelo a entrenar.

- **Estandarización o normalización** : Ajustar la escala de los datos para mejorar el rendimiento de los algoritmos sensibles a la magnitud de las variables.

- **Eliminación o transformación de valores atípicos**: Identificar y tratar con datos outliers para mejorar la robustez del modelo.

- **Nuevas características** : Creación de variables adicionales que puedan aportar información relevante al modelo.

Cada una de estas transformaciones debe ser justificada en función de su relevancia para el problema y los datos, y es importante evaluar su impacto en el rendimiento del modelo. Además, el pipeline debe ser flexible y modular para poder probar diferentes configuraciones de preprocesamiento.

In [ ]:
# Imputacion de valores nulos -> estrategias: media, mediana, moda, interpolación, etc
# Importamos las librerias necesarias:
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import FunctionTransformer
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler, OneHotEncoder, KBinsDiscretizer
from sklearn.impute import KNNImputer
import numpy as np

# Se establecen los tipos de las variables para luego asignar en los Pipelines correspondientes
num_features = ["payment", "X", "Y", "num_deliver_per_week", "num_visit_per_week", "size"]
num_features_dic = [] # Dependiendo del modelo a utilizar, esta lista se llenaría con las posibles variables a discretizar
cat_features = ["customer_type", "brand", "category", "sub_category", "segment", "package", "region_id"]

#Para crear la variable objetivo
class Obj(BaseEstimator,TransformerMixin):
  """Crea variable objetivo a partir de una la informacion del datset."""
  def __init__(self, df):
      self.df = df
    
  def fit(self, X, y=None):
      X = X.copy()
      return self
  
  def transform(self, X):
      X = X.copy()
      return X

# Para tratar con las fechas, haremos una transformación personalizada, esto ya que no consideramos correcto agregarlas a number 
# o category debido a su naturaleza -> no las estandarizamos y se usa one-hot encoding.
class Date_FeaturesExtractor(BaseEstimator, TransformerMixin):
    """Extrae variables de fecha a partir de una columna datetime."""
    def __init__(self, date_col):
        self.date_col = date_col
    
    def fit(self, X, y=None):# se calcula moda en fit para evitar dataleakage
        X = X.copy()
        self.nones = pd.to_datetime(X[self.date_col], errors="coerce").mode()[0]
        return self
    
    def transform(self, X):
        X = X.copy()
        X[self.date_col] = pd.to_datetime(X[self.date_col], errors="coerce")
        X[self.date_col] = X[self.date_col].fillna(self.nones)
        X["year"] = X[self.date_col].dt.year
        X["month"] = X[self.date_col].dt.month
        X["day"] = X[self.date_col].dt.day
        X["weekday"] = X[self.date_col].dt.weekday
        X = X.drop(columns=[self.date_col])
        return X
# Para tratar outliers usaremos el rango intercuartílico ya que se considera robusto para esta tarea
class IQR(BaseEstimator, TransformerMixin):

  def __init__(self, l):
    self.l = l
    self.inferior = -np.inf
    self.superior = np.inf

  def fit(self, X):
    q1 = X.quantile(0.25)
    q3 = X.quantile(0.75)
    RIC = q3-q1
    self.inferior = q1-self.l*RIC
    self.superior = q3+self.l*RIC
    return self

  def transform(self, X):
    for col in X.columns:
        X[col] = X[(X[col] >= self.inferior[col]) & (X[col] <= self.superior[col])][col]
    return X
      

  def set_output(self,transform='default'):
    return self
  
categoric_transformations = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")), # imputamos con las categorías más frecuentes -> porque son más probables
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

# Pipeline con discretización, sin escalado
numeric_transformations_disc = Pipeline(steps=[
    ("imputer", KNNImputer(n_neighbors=3)), # Usamos KNN porque en el lab fue el que mejores resultados dio
    ("scaler", StandardScaler()), # debido a que un gran cantidad de algoritmos de aprendizaje automático
     # / estadístico, asumen que los datos a operar se encuentran distribuidos de manera normal
    ("outlier", IQR(1.5)),  # Para outliers, 1.5 es un lambda bastante adecuado, 
    # ya que es el utilizado en los boxplots al momento de calcular los outliers.
    ("discretizer", KBinsDiscretizer(n_bins=5, encode="ordinal", strategy="quantile")) # en el caso de querer discretizar
])
# Pipeline sin discretización, con escalado
numeric_transformations_esc = Pipeline(steps=[
    ("imputer", KNNImputer(n_neighbors=3)), # Usamos KNN porque en el lab fue el que mejores resultados dio
    ("scaler", StandardScaler()), # debido a que un gran cantidad de algoritmos de aprendizaje automático
     # / estadístico, asumen que los datos a operar se encuentran distribuidos de manera normal
    ("outlier", IQR(1.5)),  # Para outliers, 1.5 es un lambda bastante adecuado, 
    # ya que es el utilizado en los boxplots al momento de calcular los outliers.
    ("scaler", StandardScaler()) # normalizamos para que más modelos puedan desempeñarse bien
])

In [ ]:
# Transformaciones personalizadas->sin discretización:
column_transformer_sin_discretizacion = ColumnTransformer(transformers=[
    ("num", numeric_transformations_esc, num_features),
    ("cat", categoric_transformations, cat_features)
])

pipeline = Pipeline(steps=[
    ("date_features", Date_FeaturesExtractor(date_col="purchase_date")),# Creamos variables
    ("preprocessor", column_transformer_sin_discretizacion)
])

In [ ]:
# Transformaciones personalizadas->con discretización:
column_transformer_con_discretizacion = ColumnTransformer(transformers=[
    ("num", numeric_transformations_esc, num_features),
    ("num_dis", numeric_transformations_disc,numeric_transformations_disc)
    ("cat", categoric_transformations, cat_features)
])

pipeline = Pipeline(steps=[
    ("date_features", Date_FeaturesExtractor(date_col="purchase_date")),# Creamos variables
    ("preprocessor", column_transformer_con_discretizacion)
])

## 📌 Baseline [0.25 puntos]

<center>
<img src="https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExN3lzeGFqZmU3NzJrZHllNjRmaHVzczJpZ29rdHdlMzVpZnQwNXo1diZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/qAtZM2gvjWhPjmclZE/giphy.gif" width="300" height="200">

En esta sección se debe construir el modelo más sencillo posible que pueda resolver el problema planteado, conocido como **Modelo baseline**. Su propósito es servir como referencia para comparar el rendimiento de los modelos más avanzados desarrollados en etapas posteriores.  

Pasos requeridos:  
- Implemente, entrene y evalúe un modelo básico utilizando un pipeline.  
- Asegúrese de incluir en el pipeline las transformaciones del preprocesamiento realizadas previamente junto con un clasificador básico.  
- Evalúe el modelo y presente el informe de métricas utilizando **`classification_report`**.  

Documente claramente cómo se creó el modelo, las decisiones tomadas y los resultados obtenidos. Este modelo será la base comparativa en las secciones posteriores.

In [37]:
df.head()

,customer_id,product_id,order_id,purchase_date,items,region_id,zone_id,customer_type,Y,X,num_deliver_per_week,num_visit_per_week,brand,category,sub_category,segment,package,size,year_week
109584,160029,1370,2629,2024-01-01,3.666667,80,5148,MAYORISTA,-46.905858,-107.991492,3,1,Brand 34,BEBIDAS CARBONATADAS,GASEOSAS,MEDIUM,BOTELLA,1.00,2024-00
110038,216498,10652,2741,2024-01-01,5.666667,80,5148,ABARROTES,-46.388138,-107.879240,4,1,Brand 34,BEBIDAS CARBONATADAS,GASEOSAS,MEDIUM,LATA,0.25,2024-00
110039,157767,11262,2622,2024-01-01,13.666667,80,5148,MAYORISTA,-46.563270,-108.003110,3,1,Brand 24,BEBIDAS CARBONATADAS,GASEOSAS,LOW,LATA,0.25,2024-00
110047,201564,1304,2697,2024-01-01,3.000000,80,5148,ABARROTES,-46.889734,-107.947970,3,1,Brand 3,BEBIDAS CARBONATADAS,GASEOSAS,MEDIUM,BOTELLA,1.00,2024-00
110051,216498,56714,2741,2024-01-01,2.333333,80,5148,ABARROTES,-46.388138,-107.879240,4,1,Brand 31,BEBIDAS CARBONATADAS,GASEOSAS,PREMIUM,BOTELLA,0.66,2024-00

## 📌 Elección de modelo [0.75 puntos]

En esta sección deben escoger un modelo que se adapte a las necesidades del negocio. Para esto, pruebe al menos 3 modelos y desarrolle los siguientes aspectos para cada uno:

- **Estructura y diferencias entre los modelos**: Explicar brevemente cada uno y sus hipérparámetros de mayor importancia.
- **Clasificadores recomendados**:
  - `LogisticRegression`
  - `KNeighborsClassifier`
  - `DecisionTreeClassifier`
  - `SVC`
  - `RandomForestClassifier`
  - `LightGBMClassifier` (del paquete `lightgbm`)
  - `XGBClassifier` (del paquete `xgboost`)
  - Otro (según lo que se estime adecuado)
  
- **Evaluación de resultados**: Se utilizará el **`classification_report`** para evaluar el rendimiento de cada modelo, destacando métricas clave como precisión, recall y F1-score. **Importante: No optimicen hiperparámetros, la idea es hacer una selección rápida del modelo.**

**Nota:** Pueden ocupar mas de 1 **instancia** de modelo para resolver el problema (e.g: (modelo_1, grupo_1), (modelo_2, grupo_2), ...).
  
A continuación, se deben responder las siguientes preguntas para evaluar el rendimiento de los modelos entrenados:

1. ¿Hay algún clasificador que supere al modelo baseline?  
2. ¿Cuál es el mejor clasificador entrenado y por qué?  
3. ¿Qué factores hacen que el mejor clasificador sea superior a los otros?  
4. En términos de `tiempo de entrenamiento`, ¿Qué modelo considera más adecuado para experimentar con grillas de optimización?

In [34]:
# Desarrolle aquí su código 
df.columns

Index(['customer_id', 'product_id', 'order_id', 'purchase_date', 'items',
       'region_id', 'zone_id', 'customer_type', 'Y', 'X',
       'num_deliver_per_week', 'num_visit_per_week', 'brand', 'category',
       'sub_category', 'segment', 'package', 'size', 'year_week'],
      dtype='object')

## 📌 Optimización de Hiperparámetros [1.0 puntos]

<center>
<img src="https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExcXJkNzdhYjlneHplaGpsbnVkdzh5dnY3Y2VyaTIzamszdGR1czJ2diZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/2rqEdFfkMzXmo/giphy.gif" width="300" height="200">

A partir de su análisis anterior, se debe proceder a optimizar el rendimiento del modelo seleccionado mediante la optimización de sus hiperparámetros. Para ello, se espera que implementen `Optuna` para optimizar no solo los hiperparámetros del modelo, sino también los de los preprocesadores utilizados (por ejemplo, OneHot Encoding, Scalers, etc.).

Al desarrollar este proceso, deberán responder las siguientes preguntas clave como mínimo:

- ¿Qué métrica decidieron optimizar y por qué?

- ¿Qué hiperparámetro tuvo un mayor impacto en el rendimiento de su modelo?

- ¿Cuánto mejoró el rendimiento del modelo después de la optimización de hiperparámetros?

In [ ]:
# Desarrolle aquí su código

## 📌 Interpretabilidad [1.0 puntos]

En esta sección, deben explicar el funcionamiento de su modelo utilizando las técnicas de interpretabilidad vistas en clase, como `SHAP`. Se espera que sean capaces de descomponer las predicciones y evaluar la importancia de los atributos y las interacciones entre ellos, con el fin de obtener una comprensión más profunda de cómo el modelo toma decisiones. 

Al desarrollar esta parte, deberán responder las siguientes preguntas clave como mínimo:

- ¿Podría explicar el funcionamiento de su modelo para una predicción en particular? Si es así, proporcione al menos tres ejemplos específicos, describiendo cómo el modelo llegó a sus decisiones y qué factores fueron más relevantes en cada caso.

- ¿Qué atributo tiene una mayor importancia en la salida de su modelo? Analice si esto tiene sentido con el problema planteado y justifique la relevancia de dicho atributo en el contexto de las predicciones que se realizan.

- ¿Existe alguna interacción entre atributos que sea relevante para el modelo? Investigue si la combinación de ciertos atributos tiene un impacto significativo en las predicciones y explíquela en **detalle**.

- ¿Podría existir sesgo hacia algún atributo en particular? Reflexione sobre la posibilidad de que el modelo esté favoreciendo ciertos atributos. Si es así, ¿cuál podría ser la causa y qué impacto podría tener esto en la predicción?

In [ ]:
# Desarrolle aquí su código

## 📌 Resultados y Conclusiones [1.0 puntos]

Para finalizar, se deben explicar los desarrollos y resultados obtenidos a lo largo de todo el proceso, desde la selección de las variables hasta la optimización de hiperparámetros e interpretación. Se espera una reflexión crítica sobre el desempeño de los modelos entrenados y una comparación entre los diferentes enfoques. Además, deberán abordar los siguientes puntos clave:

- **Análisis de métricas**: Comenten sobre las métricas obtenidas en cada etapa del modelo, destacando las más relevantes como precisión, recall, F1-score, etc. ¿Cuáles fueron los modelos más efectivos? ¿Qué diferencias notables encontró entre ellos?

- **Impacto de las decisiones tomadas**: Reflexionen sobre cómo las decisiones relacionadas con el preprocesamiento, selección de atributos y optimización de hiperparámetros influyeron en los resultados finales. ¿Hubo alguna decisión que haya tenido un impacto notable en el rendimiento?

- **Lecciones aprendidas**: Concluyan sobre las lecciones más importantes que aprendieron durante el proceso y cómo estas pueden influir en futuras iteraciones del modelo. ¿Qué se podría mejorar si se repitiera el proceso? Si tuvieran más recursos y tiempo, ¿qué otras técnicas/herramientas habrían utilizado?

> [Escriba aquí sus resultados]

Mucho éxito!

<center>
<img src="https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExaHpvOTY5Z3hpdHI3aDBpdGRueXRqamZncXp2emFrbjJ5M2s5eTR1dSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/1PMVNNKVIL8Ig/giphy.gif" width="300" height="200">